### PR TITLE
fix: prevent 'Calculation failed' flash on URL-loaded expressions

### LINKED ISSUE #111: Calculation failed
See screenshot:

Image

When I go to https://link-assistant.github.io/calculator/?q=KGV4cHJlc3Npb24lMjAlMjIoMTAwMCUyMCVEMSU4MCVEMSU4MyVEMCVCMSVEMCVCQiVEMCVCNSVEMCVCOSUyMCUyQiUyMDUwMCUyMCVEMSU4MCVEMSU4MyVEMCVCMSVEMCVCQiVEMCVCNSVEMCVCOSUyMCUyQiUyMDIwMDAlMjAlRDElODAlRDElODMlRDAlQjElRDAlQkIlRDAlQjUlRDAlQjklMjAlMkIlMjAyMCUyMFRPTiUyMCUyQiUyMDEwMDAlMjAlRDElODAlRDElODMlRDAlQjElRDAlQkIlRDAlQjUlRDAlQjkpJTIwJUQwJUIyJTIwVVNEJTIyKQ, the first thing I see for a split of a second is `Calculation failed` message.

That should not be there, instead there should be busy indicator.

As we discussed in https://github.com/link-assistant/calculator/pull/101, calculation should be executed only once, and while it executes we should show busy indicator, and only after all data fetched to fully process calculation we should be able to execute it.

We need to download all logs and data related about the issue to this repository, make sure we compile that data to `./docs/case-studies/issue-{id}` folder, and use it to do deep case study analysis (also make sure to search online for additional facts and data), in which we will reconstruct timeline/sequence of events, find root causes of the problem, and propose possible solutions (including known existing components/libraries, that solve similar problem or can help in solutions).

If there is not enough data to find actual root cause, add debug output and verbose mode if not present, that will allow us to find root cause on next iteration.

If issue related to any other repository/project, where we can report issues on GitHub, please do so. Each issue must contain reproducible examples, workarounds and suggestions for fix the issue in code.

### PR DESCRIPTION
**Pull request by konard**
## Summary

Fixes #111

When opening a calculator URL with a currency expression (e.g., converting rubles and TON to USD), users briefly see "Calculation failed" for a split second before the actual result appears. This happens because the plan message handler creates a temporary result with `success: false`, which the render logic interprets as a real error.

### Root cause

In the plan→execute pipeline introduced by PR #101, when the worker sends a `plan` message back to the UI (before rates are fetched), the handler creates a fallback base result:

```typescript
const base = prev || {
  result: '',
  steps: [],
  success: false,  // ← causes error rendering
};
```

When `prev` is `null` (first load, no cache), this sets `success: false`, triggering the error display path while the calculation is still in progress.

### Fix

1. **Plan handler** (root cause): Changed `success: false` → `success: true` in the fallback base. The plan itself succeeded — the expression was parsed and interpreted correctly. The final calculation result hasn't arrived yet, but this is not an error state.

2. **Render guard** (safety net): Changed `result ?` → `result && (result.success || !loading) ?` to prevent any error display while a calculation is in progress.

### Test added

New test: `'should NOT show "Calculation failed" when plan arrives before result (issue #111)'` — simulates a plan message arriving without a prior result and verifies no error elements are rendered.

### Case study

Detailed root cause analysis and timeline documented in `docs/case-studies/issue-111/README.md`.

## Test plan

- [x] All 210 vitest tests pass (209 existing + 1 new)
- [x] Pre-existing Rust compilation error on `main` (unrelated to this PR — `number_grammar.rs:94` type mismatch)
- [ ] Manual test: open the issue URL and verify no "Calculation failed" flash appears

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by konard** [comment]
## 🔄 Auto-restart-until-mergeable Log (iteration 1)
This log file contains the complete execution trace of the AI solution draft process.

### 💰 **Cost estimation:**
- Public pricing estimate: $1.202883
- Calculated by Anthropic: $0.592188 USD
- Difference: $-0.610695 (-50.77%)

### 🤖 **Models used:**
- Tool: Claude
- Requested: `opus`
- **Model: Claude Opus 4.6** (`claude-opus-4-6`)

### 📎 **Log file uploaded as Gist** (1906KB)
- [View complete solution draft log](https://gist.githubusercontent.com/konard/8fca685a124a47bbe92718e7790ad092/raw/a3790618369a89d06035e199255ac29b1028f4e3/solution-draft-log-pr-1774220873613.txt)

---
*Now working session is ended, feel free to review and add any feedback on the solution draft.*
